baseURL = 'https://267962portfolio.org/'
languageCode = 'cz-cs'
title = 'ZPC portfolio'
theme = "hugo-bearblog-master"

[menu]

  [[menu.main]]
    name = "Úvod"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Galerie projektů"
    title = "Galerie projektů"
    url = "/projekty/"
    weight = 2

  [[menu.main]]
    name = "O mně"
    url = "/posts/my-info/"
    weight = 3

[markup.goldmark.renderer]
unsafe = true
